Add logging
AndreyElagin/http-server-task pull request #16
Opened 2020-02-11 12:40 UTC by mrPTqp

2020-02-11 22:48 UTC, daddyingrave requested changes

2020-02-11 22:48 UTC, AndreyElagin commented on src/main/java/com/study/server/ConfigurationReaderImpl.java
> +                    "Parameters obtained from configuration file:\r\n"
`\n` достаточно, замени везде

2020-02-11 22:48 UTC, AndreyElagin commented on src/main/java/com/study/server/ConfigurationReaderImpl.java
> +    private static final Logger LOGGER = Logger.getLogger(ConfigurationReaderImpl.class.getName());
Использую везде подобную форму, согласно уровня логгирования:
```
private static final Logger log = Logger.getLogger(ConfigurationReaderImpl.class.getName());
log.severe("msg");
log.warning("msg");
итд
```

2020-02-11 22:48 UTC, AndreyElagin commented on src/main/java/com/study/server/ConfigurationReaderImpl.java
> +                    "Parameters obtained from configuration file:\r\n"
и вообще не надо этих переносов нигде, делай все в одну строку.

2020-02-12 06:45 UTC, mrPTqp commented on src/main/java/com/study/server/ConfigurationReaderImpl.java
> +                    "Parameters obtained from configuration file:\r\n"
исправлено

2020-02-12 06:45 UTC, mrPTqp commented on src/main/java/com/study/server/ConfigurationReaderImpl.java
> +    private static final Logger LOGGER = Logger.getLogger(ConfigurationReaderImpl.class.getName());
исправлено

2020-02-12 10:15 UTC, daddyingrave approved these changes

2020-02-12 10:15 UTC, merged