42-http-parser
AndreyElagin/http-server-task pull request #3
Opened 2019-12-24 14:33 UTC by mrPTqp

2019-12-24 22:02 UTC, daddyingrave requested changes

2019-12-24 22:02 UTC, daddyingrave commented on src/main/java/com/study/server/Main.java
> +        String sourceDir = System.getenv().get("SitesAndConfigDirectory");
У формата названий переменных окружения обычно такой же формат как и статических констант в java. Тобишь апперкейс и андрескор `_` в качестве разделителя

2019-12-24 22:02 UTC, daddyingrave commented on src/main/java/com/study/server/Main.java
>              Integer numberOfThreads = Integer.parseInt(properties.getProperty("numberOfThreads"));
Давай для имен проперти использовать примерно такой же подход как [здесь](https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html)
Тоесть у тебя будут типа группы вложенности, в данной ситуации можно так сделать server.pool-size
Группы разделяешь между собой, а вместо пробела дефис

2019-12-24 22:02 UTC, daddyingrave commented on src/main/java/com/study/server/http/HttpRequestParser.java
> +        Pattern methodPattern = Pattern.compile("^[A-Z]+");
Объедини в один паттерн methodPattern, pathPattern, parametersPattern и protocolPattern и используй [named capturing groups](https://stackoverflow.com/questions/415580/regex-named-groups-in-java)

2019-12-24 22:02 UTC, daddyingrave commented on src/main/java/com/study/server/http/HttpRequestParser.java
> +
По всем паттернам общее требование, посмотри пожалуйста, какие ограничения есть согласно спецификации (или хотя бы ее трактованиям на stackoverflow), они у тебя получились сильно широкие особенно headersPattern. Не забудь про url encode (погугли про это), в стандартной библиотеке вроде есть функции и для url кодирования и декодирования и если они есть то будь добр поддержать русский язык в заголовках и квери параметрах

2019-12-24 22:02 UTC, daddyingrave commented on src/main/java/com/study/server/http/HttpRequestParser.java
> +    public Request parse(InputStream in) {
Очень длинный метод. Все паттерны должны быть вынесены на уровень статических констант класса, парсинг отдельных элементов запроса должен быть оформлен как набор отдельных приватных методов.

2019-12-24 22:02 UTC, daddyingrave commented on src/main/java/com/study/server/http/HttpRequestParser.java
> +            String first = br.readLine();
Каждая строка должна парсится только один раз.

2019-12-24 22:02 UTC, daddyingrave commented on src/main/java/com/study/server/http/HttpRequestParser.java
> +                path = "/index.html";
Вроде договаривались что не будем этого делать на этом уровне

2019-12-24 22:02 UTC, daddyingrave commented on src/main/java/com/study/server/http/HttpRequestParser.java
> +                String[] partsOfHeaders = matcher.group().split(": ");
Старайся не использовать в названиях переменных `of`
В данном случае можно сделать либо headersParts либо просто parts, тем более я не очень понимаю о чем тут идет речь :)

2019-12-24 22:02 UTC, daddyingrave commented on src/main/java/com/study/server/http/HttpRequestParser.java
> +                String[] partsOfHeaders = matcher.group().split(": ");
Если здесь речь о том что это ключ значение, то назови это headersPair или просто pair

2019-12-24 22:02 UTC, daddyingrave commented on src/main/java/com/study/server/http/HttpRequestParser.java
> +                String[] partsOfHeaders = matcher.group().split(": ");
И если ты ожидаешь что после сплита будет именно два элемента, то это стоит [проверить](https://docs.oracle.com/javase/8/docs/api/java/lang/String.html#split-java.lang.String-int-)

2019-12-24 22:02 UTC, daddyingrave commented on src/main/java/com/study/server/http/HttpRequestParser.java
> +            matcher = hostPattern.matcher(nonFormattedHost);
Насколько понимаю у хоста может быть еще порт и вроде ты это не обрабатываешь

2019-12-24 22:02 UTC, daddyingrave commented on src/main/java/com/study/server/http/HttpRequestParser.java
> +            while (curLine != null) {
Вроде договаривались не вычитывать боди здесь

2019-12-24 22:02 UTC, daddyingrave commented on src/main/java/com/study/server/http/HttpRequestParser.java
> +            if (sb.toString().length() > 0 & !method.equals("GET") & !method.equals("DELETE")) {
Здесь это вроде безопасно но приучайся всегда делать проверку на equals наоборт. Тоесть когда у тебя есть некая константа и значение которое ты откуда то получил, всегда вызывай метод equals на константе, тем самым ты понижаешь риск nullpointer

2019-12-24 22:02 UTC, daddyingrave commented on src/main/java/com/study/server/http/HttpRequestParser.java
> +            if (sb.toString().length() > 0 & !method.equals("GET") & !method.equals("DELETE")) {
И заведи под методы Enum

2019-12-24 22:02 UTC, daddyingrave commented on src/main/java/com/study/server/http/Request.java
>  public class Request {
Пусть это будет HttpRequest

2019-12-24 22:02 UTC, daddyingrave commented on src/main/java/com/study/server/http/Request.java
>  public class Request {
И давай сделаем этот класс полностью иммутабельным. Тоесть у него совсем не будет сеттеров. А для построения нового инстанса ты будешь использовать этот [паттерн](https://refactoring.guru/ru/design-patterns/builder)

2019-12-24 22:02 UTC, daddyingrave commented on src/main/java/com/study/server/http/Request.java
>          return headers;
Для того чтобы класс был полностью иммутабельным ты не должен выдавать ссылки на его поля наружу. Поэтому когда заходит речь о том чтобы вернуть коллекцию каких либо элементов ты должен создать копию оригинальной коллекции и вернуть уже ее. Посмотри какие встроенные способы есть для этого в джава

2019-12-24 22:02 UTC, daddyingrave commented on src/main/java/com/study/server/http/Request.java
>          return queryParameters;
см. выше

2019-12-24 22:02 UTC, daddyingrave commented on src/test/java/com/study/server/http/HttpRequestParserTest.java
> +        Request expectedRequest = new Request();
Сделай утильный метод/методы которые бы генерировали реквест, слишком много подготовительного кода в тестах

2019-12-24 22:02 UTC, daddyingrave commented on src/main/java/com/study/server/http/HttpRequestParser.java
> +    public static HttpRequestParser getParser() {
Короч забей хуй на такую реализацию синглтона (как минимум потому что она косячная) пусть метод parse будет статическим а getParser выкинь

2019-12-24 22:02 UTC, daddyingrave commented on src/test/java/com/study/server/http/HttpRequestParserTest.java
> +        InputStream in1 = new ByteArrayInputStream(data1);
Хочу чтобы ты InputStream'ы делал из файлов. Создай для каждого запроса текстовый файл, который будешь в тесте вычитывать и парсить

2019-12-24 22:02 UTC, daddyingrave commented on src/test/java/com/study/server/http/HttpRequestParserTest.java
> +        assertEquals(expectedRequest.getMethod(), request.getMethod());
дабы избежать такой поеботы как с 54 по 60 определи метод equals на реквесте

2019-12-24 22:02 UTC, daddyingrave commented on src/test/java/com/study/server/http/HttpRequestParserTest.java
> +        expectedRequest.setPath("/index.html");
и вот то что дальше в тесте идет тоже странно. помнишь я тебе рассказывал про условные секции given when then, так вот, я не просто так про это рассказывал, тесты должно быть ОЧЕНЬ легко читать, а у тебя тут идет посмотоянное мутирование стейта реквеста, трудно мне (

2019-12-24 22:02 UTC, daddyingrave commented on src/test/java/com/study/server/http/RequestLineConstructor.java
> +    RequestLineConstructor(String method, String path, Map<String, String> queryParameters, String protocol,
```
RequestLineConstructor(String method,
                                        String path, 
                                        Map<String, String> queryParameters, 
                                        String protocol,
                                        String host,
                                        Map<String, String> headers, 
                                        String body) {
 ...
}
```

2019-12-24 22:02 UTC, AndreyElagin commented on src/test/java/com/study/server/http/RequestLineConstructor.java
> +    RequestLineConstructor(String method, String path, Map<String, String> queryParameters, String protocol,
я хз почему он так странно отображет форматирование но смысл в том что когда аргументов становится много то для лучшей читаемсти стоит их выровнять примрно таким образом. 
все должно быть выровнено по `String method`

2019-12-24 22:02 UTC, AndreyElagin commented on src/test/java/com/study/server/http/RequestLineConstructor.java
> +                sb.append(pair.getKey()).
так я не буду в целом читать пока что здесь написано, но хуле ты точки не переносишь? )

2019-12-25 07:03 UTC, mrPTqp commented on src/main/java/com/study/server/Main.java
> +        String sourceDir = System.getenv().get("SitesAndConfigDirectory");
А на каком варианте мы всё-таки остановимся, на переменных окружения, или на параметрах запуска? Или нужно и так и так?

2019-12-25 07:04 UTC, mrPTqp commented on src/main/java/com/study/server/Main.java
>              Integer numberOfThreads = Integer.parseInt(properties.getProperty("numberOfThreads"));
Я не против, но для чего? У меня в сервере предполагаются какие-то другие группы?

2019-12-25 11:39 UTC, mrPTqp commented on src/main/java/com/study/server/http/HttpRequestParser.java
> +            matcher = hostPattern.matcher(nonFormattedHost);
А мне надо это обрабатывать?

2019-12-25 11:39 UTC, mrPTqp commented on src/main/java/com/study/server/http/HttpRequestParser.java
> +                path = "/index.html";
А я чот помню, что будем) давай решим да или нет?

2019-12-25 11:41 UTC, mrPTqp commented on src/main/java/com/study/server/http/HttpRequestParser.java
> +            while (curLine != null) {
А где его тогда вычитывать? Помню договаривались не обрабатывать его никак, но вычитать то надо, не?

2019-12-25 15:10 UTC, AndreyElagin commented on src/main/java/com/study/server/Main.java
> +        String sourceDir = System.getenv().get("SitesAndConfigDirectory");
Давай сейчас только на переменных окружения. Добавлю в требования

2019-12-25 15:10 UTC, AndreyElagin commented on src/main/java/com/study/server/Main.java
>              Integer numberOfThreads = Integer.parseInt(properties.getProperty("numberOfThreads"));
для того

2019-12-25 15:10 UTC, AndreyElagin commented on src/main/java/com/study/server/Main.java
>              Integer numberOfThreads = Integer.parseInt(properties.getProperty("numberOfThreads"));
Делаем как деды делали

2019-12-25 15:10 UTC, AndreyElagin commented on src/main/java/com/study/server/Main.java
>              Integer numberOfThreads = Integer.parseInt(properties.getProperty("numberOfThreads"));
Ну тип контракт такой

2019-12-25 15:11 UTC, AndreyElagin commented on src/main/java/com/study/server/http/HttpRequestParser.java
> +                path = "/index.html";
Не будем

2019-12-25 15:12 UTC, AndreyElagin commented on src/main/java/com/study/server/http/HttpRequestParser.java
> +            matcher = hostPattern.matcher(nonFormattedHost);
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Host

2019-12-25 15:15 UTC, AndreyElagin commented on src/main/java/com/study/server/http/HttpRequestParser.java
> +            while (curLine != null) {
Под необрабатывать никак я предполагал что ты не будешь трогать InputStream после того как вычитаешь из него все до body. Просто там же необязательно будет обычная строка, там может быть картинка base64 например, и сначала представлять все это в виде строки а потом декодить в картинку будет дорого. Вообще конечно правильно наверное на основе mime type декодить боди, но мы это потом сделаем и мб на другом уровне.

2019-12-30 05:09 UTC, mrPTqp commented on src/main/java/com/study/server/http/HttpRequestParser.java
> +    public static HttpRequestParser getParser() {
А почему такая реализация синглтона плоха? Какая реализация хорошая?

2019-12-30 07:39 UTC, AndreyElagin commented on src/main/java/com/study/server/http/HttpRequestParser.java
> +    public static HttpRequestParser getParser() {
А бля сорян, она рабочая но бессмысленная. Вот [здесь](https://habr.com/en/post/129494/) хороший разбор того какие есть базовые подходы.

2020-01-10 06:43 UTC, mrPTqp commented on src/main/java/com/study/server/Main.java
> +        String sourceDir = System.getenv().get("SitesAndConfigDirectory");
исправлено

2020-01-10 06:43 UTC, mrPTqp commented on src/main/java/com/study/server/Main.java
>              Integer numberOfThreads = Integer.parseInt(properties.getProperty("numberOfThreads"));
исправлено

2020-01-10 06:43 UTC, mrPTqp commented on src/main/java/com/study/server/http/HttpRequestParser.java
> +        Pattern methodPattern = Pattern.compile("^[A-Z]+");
исправлено

2020-01-10 06:45 UTC, mrPTqp commented on src/main/java/com/study/server/http/HttpRequestParser.java
> +
Не скажу, что нашел отдельные требования для path или query, поэтому не могу сказать, что составленные мной регулярки очень хороши, но, по крайней мере, они допускают только ASCII, как и договорились. URL-encode в итоге не реализован пока, соответственно русский тоже не поддерживается

2020-01-10 06:45 UTC, mrPTqp commented on src/main/java/com/study/server/http/HttpRequestParser.java
> +    public Request parse(InputStream in) {
исправлено

2020-01-10 06:45 UTC, mrPTqp commented on src/main/java/com/study/server/http/HttpRequestParser.java
> +            String first = br.readLine();
исправлено

2020-01-10 06:45 UTC, mrPTqp commented on src/main/java/com/study/server/http/HttpRequestParser.java
> +                path = "/index.html";
исправлено

2020-01-10 06:46 UTC, mrPTqp commented on src/main/java/com/study/server/http/HttpRequestParser.java
> +                String[] partsOfHeaders = matcher.group().split(": ");
исправлено

2020-01-10 06:58 UTC, mrPTqp commented on src/main/java/com/study/server/http/HttpRequestParser.java
> +            matcher = hostPattern.matcher(nonFormattedHost);
исправлено

2020-01-10 06:58 UTC, mrPTqp commented on src/main/java/com/study/server/http/HttpRequestParser.java
> +            while (curLine != null) {
исправлено, пока что боди не обрабатывается вовсе

2020-01-10 06:59 UTC, mrPTqp commented on src/main/java/com/study/server/http/HttpRequestParser.java
> +            if (sb.toString().length() > 0 & !method.equals("GET") & !method.equals("DELETE")) {
исправлено

2020-01-10 06:59 UTC, mrPTqp commented on src/main/java/com/study/server/http/Request.java
>  public class Request {
исправлено

2020-01-10 06:59 UTC, mrPTqp commented on src/main/java/com/study/server/http/Request.java
>          return headers;
исправлено

2020-01-10 06:59 UTC, mrPTqp commented on src/main/java/com/study/server/http/Request.java
>          return queryParameters;
исправлено

2020-01-10 06:59 UTC, mrPTqp commented on src/test/java/com/study/server/http/HttpRequestParserTest.java
> +        Request expectedRequest = new Request();
исправлено

2020-01-10 06:59 UTC, mrPTqp commented on src/main/java/com/study/server/http/HttpRequestParser.java
> +    public static HttpRequestParser getParser() {
исправлено

2020-01-10 06:59 UTC, mrPTqp commented on src/test/java/com/study/server/http/HttpRequestParserTest.java
> +        InputStream in1 = new ByteArrayInputStream(data1);
исправлено

2020-01-10 06:59 UTC, mrPTqp commented on src/test/java/com/study/server/http/HttpRequestParserTest.java
> +        assertEquals(expectedRequest.getMethod(), request.getMethod());
исправлено

2020-01-10 07:00 UTC, mrPTqp commented on src/test/java/com/study/server/http/HttpRequestParserTest.java
> +        expectedRequest.setPath("/index.html");
исправлено

2020-01-10 07:00 UTC, mrPTqp commented on src/test/java/com/study/server/http/RequestLineConstructor.java
> +    RequestLineConstructor(String method, String path, Map<String, String> queryParameters, String protocol,
исправлено

2020-01-10 07:00 UTC, mrPTqp commented on src/test/java/com/study/server/http/RequestLineConstructor.java
> +                sb.append(pair.getKey()).
я модный прост. этот кусок кода удален

2020-01-10 07:17 UTC, AndreyElagin commented on src/main/java/com/study/server/Main.java
> +        String sourceDir = System.getenv().get("SitesAndConfigDirectory");
Вообще я что то протупил, ты на самом деле можешь примерно так делать https://stackoverflow.com/questions/30889478/passing-environment-variable-to-a-java-class-in-command-line так что в доп требованиях смысла нет

2020-01-10 14:47 UTC, mrPTqp commented on src/main/java/com/study/server/Main.java
> +        String sourceDir = System.getenv().get("SitesAndConfigDirectory");
Это ты имеешь ввиду, что я могу путь передать через параметр запуска? И чот не пойму как это связано с доп требованиями...

2020-01-11 08:36 UTC, AndreyElagin commented on src/main/java/com/study/server/Main.java
> +        String sourceDir = System.getenv().get("SitesAndConfigDirectory");
Я сейчас про то что нет смысла обрабатывать кастомные параметры запуска если уже есть встроенные и они нормально обрабатываются jvm и при этом тебе ничего не придется дополнительно делать. Сплошные плюсы же :)

2020-01-11 09:04 UTC, AndreyElagin commented on src/test/java/com/study/server/http/HttpRequestParserTest.java
> +        try {
А зачем ты в тестах все оборачиваешь в try/catch?
Удали их, junit их перехватит за тебя

2020-01-11 09:33 UTC, AndreyElagin commented on src/main/java/com/study/server/http/HttpRequestParser.java
> +            var method = methodParse(matcher);
Короч последняя доебка :)
Мне не нравится что ты в методы которые что то парсят передаешь матчер и внутри этих методов зашита логика: 
а) связанная с тем надо что то парсить или нет
б) управляющая флоу матчера.
Сначала по поводу флоу матчера. У тебя получается что ты не можешь вызвать методы для парсинга первой строки в порядке отличном от того который у тебя сейчас объявлен в коде, потому что `pathParse` и `queryParse` уже ожидают что на матчере вызван метод `find`, а это нехорошо, мутировать стейт чего либо стоит стараться всегда только в локальном контексте, даже если речь идет о приватных методах. 
Теперь по поводу пункта `а`. Мне кажется что правильнее принимать решение о необходимости парсинга пути или квери в основном флоу метода `parse`. Тоесть смотри, ты сначала матчишь первую строку против своего паттерна, потом тут же делаешь `find` и далее делаешь примерно следующее:
```
var method = matcher.group("method");
if (!method.isEmpty()) {
    builder.setMethod(methodParse(method));
} else {
    throw new BadRequestException("Method is mandatory!");
}
```
Ну и в таком же духе для всех последующих.

2020-01-11 18:26 UTC, mrPTqp commented on src/main/java/com/study/server/http/HttpRequestParser.java
> +            var method = methodParse(matcher);
Исправлено

2020-01-11 18:26 UTC, mrPTqp commented on src/test/java/com/study/server/http/HttpRequestParserTest.java
> +        try {
Исправлено

2020-01-12 09:15 UTC, daddyingrave requested changes

2020-01-12 09:15 UTC, AndreyElagin commented on src/main/java/com/study/server/http/HttpRequestParser.java
> +            if (curLine.contains(" /")) {
Зачем делать проверять строку на то что она содержит слэш если у тебя уже есть отработавший матчер, который должен содержать значение `path` в случае если оно там было? Ну тоесть не проще ли сделать как на 35 строке, чтобы не выполнять лишней работы с поиском слэша в строке?

2020-01-12 09:15 UTC, AndreyElagin commented on src/main/java/com/study/server/http/HttpRequestParser.java
> +            if (curLine.contains("?")) {
см. выше

2020-01-12 09:15 UTC, AndreyElagin commented on src/main/java/com/study/server/http/HttpRequestParser.java
> +            builder.setProtocol(protocolCheck(protocol));
обычно методы типа `checkSomething` что то проверяет и либо ничего не возвращают либо возвращают `boolean`. У тебя тут 2 варианта, либо поменять возвращаемое значение на `void` и выполнять эту проверку на строчку выше, либо придумать такое название метода, которое будет отражать факт того, что выполнятеся проверка и возвращается значение. Я хз почему, но обычно в таком случае методы называют `validateSomething`. В данном случае я больше за первый вариант.

2020-01-12 09:15 UTC, AndreyElagin commented on src/main/java/com/study/server/http/HttpRequestParser.java
> +    private static String hostParse(Map<String, String> headers) {
Ну и раз я все еще продолжаю доебываться, то как по мне для такого метода больше подойдет название `extractHost`

2020-01-12 09:15 UTC, AndreyElagin commented on src/main/java/com/study/server/http/HttpRequestParser.java
> +    private static String portParse(Map<String, String> headers) {
`extractPort`

2020-01-12 16:05 UTC, mrPTqp commented on src/main/java/com/study/server/http/HttpRequestParser.java
> +            if (curLine.contains(" /")) {
исправлено

2020-01-12 16:05 UTC, mrPTqp commented on src/main/java/com/study/server/http/HttpRequestParser.java
> +            if (curLine.contains("?")) {
исправлено

2020-01-12 16:05 UTC, mrPTqp commented on src/main/java/com/study/server/http/HttpRequestParser.java
> +            builder.setProtocol(protocolCheck(protocol));
исправлено

2020-01-12 16:05 UTC, mrPTqp commented on src/main/java/com/study/server/http/HttpRequestParser.java
> +    private static String hostParse(Map<String, String> headers) {
исправлено

2020-01-12 16:05 UTC, mrPTqp commented on src/main/java/com/study/server/http/HttpRequestParser.java
> +    private static String portParse(Map<String, String> headers) {
исправлено

2020-01-12 16:12 UTC, daddyingrave approved these changes

2020-01-12 16:13 UTC, merged