45 config reader
AndreyElagin/http-server-task pull request #4
Opened 2020-01-20 06:39 UTC by mrPTqp

2020-01-20 19:51 UTC, daddyingrave requested changes

2020-01-20 19:51 UTC, AndreyElagin commented on src/main/java/com/study/server/ConfigurationReader.java
> +    Map<String, String> createMapping();
`readMappings`

2020-01-20 19:51 UTC, AndreyElagin commented on src/main/java/com/study/server/ConfigurationReaderImpl.java
> +        } catch (Exception e) {
А почему здесь должено вылететь исключение?

2020-01-20 19:51 UTC, AndreyElagin commented on src/main/java/com/study/server/ServerConfiguration.java
> +public class ServerConfiguration {
Давай все таки продолжать пользоваться иммутабельными структурами

2020-01-20 19:51 UTC, AndreyElagin commented on src/main/java/com/study/server/ServerConfiguration.java
> +public class ServerConfiguration {
Никаких сеттеров

2020-01-20 19:51 UTC, AndreyElagin commented on src/main/java/com/study/server/ConfigurationReaderImpl.java
> +            return config;
Не очень понял что ты хочешь здесь вернуть? Если ты не сможешь прочитать файл, то ты потом упадешь с NullPointer в лучшем случае

2020-01-20 19:51 UTC, AndreyElagin commented on src/main/java/com/study/server/ConfigurationReaderImpl.java
> +            port = Integer.parseInt(properties.getProperty("server.port"));
а если Integer не сможешь распрасить?

2020-01-20 19:51 UTC, AndreyElagin commented on src/main/java/com/study/server/ConfigurationReaderImpl.java
> +        Map<String, String> mapping = new HashMap<>();
Где можно (а можно везде) используем иммутабельные структуры. `Map.of()`

2020-01-20 19:51 UTC, AndreyElagin commented on src/main/java/com/study/server/ConfigurationReaderImpl.java
> +        Pattern jsonHostPattern = Pattern.compile(
Короч давай все таки откажемся от поддержки этого файла (site-name.json). Читай имя хоста из имени папки.

2020-01-20 19:51 UTC, AndreyElagin commented on src/main/java/com/study/server/ConfigurationReaderImpl.java
> +        Pattern pathHostPattern = Pattern.compile(
Переиспользуй уже написанный паттерн. Можешь для этого выделить отдельный класс с константами и поместить туда все паттерны

2020-01-20 19:51 UTC, AndreyElagin commented on src/main/java/com/study/server/Main.java
> +        HttpServerImpl server = new HttpServerImpl(config.getPort(), config.getPoolSize());
Не вижу смысла передавать отдельными аргуменами хост и порт, передавай туда сразу `ServerConfiguration`

2020-01-20 19:51 UTC, AndreyElagin commented on src/main/java/com/study/server/ConfigurationReaderImpl.java
> +            throw new BadConfigException("The configuration directory does not contain valid site directories");
1. Не вижу смысла здесь в кастомном исключении. Больше подходить что то в стиле FileNotFoundException.
2. Когда ты 2 раза с разницей в 4 строчки используешь идентичные строки, тебя это должно навести на какие нибудь мысли :)

2020-01-20 19:51 UTC, AndreyElagin commented on src/main/java/com/study/server/exceptions/BadConfigException.java
> +public class BadConfigException extends RuntimeException {
Скорее всего это исключение надо удалить.

2020-01-21 06:44 UTC, mrPTqp commented on src/main/java/com/study/server/ConfigurationReaderImpl.java
> +        } catch (Exception e) {
Потому что я не посмотрел сигнатуру метода:( Он не выкинет исключение, он вернет null, если такой переменной окружения не будет обнаружено. Но я думаю я всё равно должен бросить исключение, ведь без этой переменной сервер работать не сможет. Правильно я думаю?

2020-01-21 06:49 UTC, mrPTqp commented on src/main/java/com/study/server/ConfigurationReaderImpl.java
> +            return config;
Я ж типа чо сделал, я создал обертку ServerConfiguration, в которой по умолчанию, пока никто не засэтил порт и пулСайз они равны дефолтным значениям. Вот типа этот ServerConfiguration с дефолтными значениями я и хотел вернуть. Не выйдет так, да?

2020-01-21 06:50 UTC, mrPTqp commented on src/main/java/com/study/server/ServerConfiguration.java
> +public class ServerConfiguration {
Крч опять через конструктор все значения передаем, да?

2020-01-21 06:57 UTC, mrPTqp commented on src/main/java/com/study/server/ConfigurationReaderImpl.java
> +            port = Integer.parseInt(properties.getProperty("server.port"));
Что ты имеешь ввиду? Что нужно предусмотреть обработку исключения при парсинге Integer?

2020-01-21 06:58 UTC, mrPTqp commented on src/main/java/com/study/server/ConfigurationReaderImpl.java
> +        Map<String, String> mapping = new HashMap<>();
исправлено

2020-01-21 06:58 UTC, mrPTqp commented on src/main/java/com/study/server/ConfigurationReaderImpl.java
> +        Pattern jsonHostPattern = Pattern.compile(
принято

2020-01-21 07:20 UTC, mrPTqp commented on src/main/java/com/study/server/ConfigurationReaderImpl.java
> +            throw new BadConfigException("The configuration directory does not contain valid site directories");
1. Ну да, перехватывать выше мне его не придется. Разве что было бы просто нагляднее при запуске сервера получить исключение из названия которого было бы понятно чо случилось, с другой стороны это можно описать и в сообщении.
2. Навело. И щас также смотрю и не понимаю как мне слить это воедино :(

2020-01-21 07:30 UTC, AndreyElagin commented on src/main/java/com/study/server/ConfigurationReaderImpl.java
> +        } catch (Exception e) {
Да правильно. Вот только опять же не надо кастомное исключение придумывать, брось какой нить `IllegalArgumentException` или что то более подходящее если найдешь

2020-01-21 07:30 UTC, AndreyElagin commented on src/main/java/com/study/server/ServerConfiguration.java
> +public class ServerConfiguration {
да

2020-01-21 07:39 UTC, AndreyElagin commented on src/main/java/com/study/server/ServerConfiguration.java
> +public class ServerConfiguration {
Конструктор или билдер. И убери статик модификатор, все должно быть динимическим, но `final`

2020-01-21 07:39 UTC, AndreyElagin commented on src/main/java/com/study/server/ConfigurationReaderImpl.java
> +            port = Integer.parseInt(properties.getProperty("server.port"));
Ну вообще наверное нет. и так должно тут вылететь понятно исключение

2020-01-21 07:39 UTC, AndreyElagin commented on src/main/java/com/study/server/ConfigurationReaderImpl.java
> +            return config;
Это стоит сделать явно. Пусть у объекта `ServerConfiguration` будет 2 конструктора, один будет инициализиовать дефолтные значения другой значения из пропертей

2020-01-21 07:39 UTC, AndreyElagin commented on src/main/java/com/study/server/ConfigurationReaderImpl.java
> +            throw new BadConfigException("The configuration directory does not contain valid site directories");
1. У тебя в исключении есть сообщение, ты туда его передашь и все поймешь 
2. Ну сделай просто стат константу с сообщением, все по стандартной схеме

2020-01-21 08:39 UTC, mrPTqp commented on src/main/java/com/study/server/ConfigurationReaderImpl.java
> +            port = Integer.parseInt(properties.getProperty("server.port"));
Слушай, а вот какую логику мы здесь предусмотрим? Если файл server-config.properties существует, но в нем указаны неправильные параметры, то чо? То сервер падает, или сервер поднимается, но с дефолтными параметрами? Мне кажется лучше, если он будет падать...

2020-01-21 09:29 UTC, AndreyElagin commented on src/main/java/com/study/server/ConfigurationReaderImpl.java
> +            port = Integer.parseInt(properties.getProperty("server.port"));
Обычно всегда сервера стартуют с дефолтными настройками

2020-01-21 14:04 UTC, mrPTqp commented on src/main/java/com/study/server/ConfigurationReader.java
> +    Map<String, String> createMapping();
Исправлено

2020-01-21 14:04 UTC, mrPTqp commented on src/main/java/com/study/server/ConfigurationReaderImpl.java
> +        } catch (Exception e) {
Исправлено

2020-01-21 14:05 UTC, mrPTqp commented on src/main/java/com/study/server/ServerConfiguration.java
> +public class ServerConfiguration {
Исправлено

2020-01-21 14:05 UTC, mrPTqp commented on src/main/java/com/study/server/ConfigurationReaderImpl.java
> +            return config;
Исправлено

2020-01-21 14:05 UTC, mrPTqp commented on src/main/java/com/study/server/ConfigurationReaderImpl.java
> +            port = Integer.parseInt(properties.getProperty("server.port"));
Исправлено

2020-01-21 14:05 UTC, mrPTqp commented on src/main/java/com/study/server/ConfigurationReaderImpl.java
> +        Pattern jsonHostPattern = Pattern.compile(
Исправлено

2020-01-21 14:06 UTC, mrPTqp commented on src/main/java/com/study/server/ConfigurationReaderImpl.java
> +        Pattern pathHostPattern = Pattern.compile(
Не исправлено. Не могу придумать обобщенного регулярного выражения для парсинга хоста из пути и из хедэров одновременно. Создал отдельный класс для регулярок.

2020-01-21 14:06 UTC, mrPTqp commented on src/main/java/com/study/server/Main.java
> +        HttpServerImpl server = new HttpServerImpl(config.getPort(), config.getPoolSize());
Исправлено

2020-01-21 14:06 UTC, mrPTqp commented on src/main/java/com/study/server/ConfigurationReaderImpl.java
> +            throw new BadConfigException("The configuration directory does not contain valid site directories");
Исправлено

2020-01-21 14:06 UTC, mrPTqp commented on src/main/java/com/study/server/exceptions/BadConfigException.java
> +public class BadConfigException extends RuntimeException {
Исправлено

2020-01-21 19:48 UTC, daddyingrave requested changes

2020-01-21 19:48 UTC, AndreyElagin commented on src/main/java/com/study/server/ConfigurationReaderImpl.java
> +        return Collections.unmodifiableMap(mutableMappings);
`Map.copyOf()`

2020-01-21 19:48 UTC, AndreyElagin commented on src/main/java/com/study/server/ConfigurationReaderImpl.java
> +    private static final String MESSAGE = "The configuration directory " +
`ERROR_TEXT` или как то так

2020-01-21 19:48 UTC, AndreyElagin commented on src/main/java/com/study/server/ConfigurationReaderImpl.java
> +        Map<String, String> mutableMappings = new HashMap<>();
просто `mappings`

2020-01-21 19:48 UTC, AndreyElagin commented on src/main/java/com/study/server/ConfigurationReaderImpl.java
> +            var hostMatcher = ParsingPatterns.pathHostPattern.matcher(curPath.toString());
`dir.getPath()`

2020-01-21 19:48 UTC, AndreyElagin commented on src/main/java/com/study/server/ConfigurationReaderImpl.java
> +                System.out.println("No directory matching host pattern was found in the path " + curPath.toString());
Хорошая попытка, но нет. Логгирование мы потом доделаем

2020-01-21 19:48 UTC, AndreyElagin commented on src/main/java/com/study/server/Main.java
> +        Map<String, String> mapping = cr.readMappings();
mapping**s**

2020-01-21 19:48 UTC, AndreyElagin commented on src/main/java/com/study/server/ServerConfiguration.java
> +    private int port;
final?

2020-01-21 19:48 UTC, AndreyElagin commented on src/main/java/com/study/server/ServerConfiguration.java
> +    private int poolSize;
final?

2020-01-21 19:48 UTC, AndreyElagin commented on src/main/java/com/study/server/ServerConfiguration.java
> +    private final int defaultPort = 3333;
Нет смысла выделять это в поля. Инициализируй дефолты в дефолтном конструкторе

2020-01-21 19:48 UTC, AndreyElagin commented on src/main/java/com/study/server/utils/ParsingPatterns.java
> +public class ParsingPatterns {
HttpPatterns

2020-01-22 12:06 UTC, mrPTqp commented on src/main/java/com/study/server/ConfigurationReaderImpl.java
> +        return Collections.unmodifiableMap(mutableMappings);
исправлено

2020-01-22 12:06 UTC, mrPTqp commented on src/main/java/com/study/server/ConfigurationReaderImpl.java
> +    private static final String MESSAGE = "The configuration directory " +
этот код исключен, но мысль понял

2020-01-22 12:06 UTC, mrPTqp commented on src/main/java/com/study/server/ConfigurationReaderImpl.java
> +        Map<String, String> mutableMappings = new HashMap<>();
исправлено

2020-01-22 12:06 UTC, mrPTqp commented on src/main/java/com/study/server/ConfigurationReaderImpl.java
> +            var hostMatcher = ParsingPatterns.pathHostPattern.matcher(curPath.toString());
исправлено

2020-01-22 12:07 UTC, mrPTqp commented on src/main/java/com/study/server/ConfigurationReaderImpl.java
> +                System.out.println("No directory matching host pattern was found in the path " + curPath.toString());
исключил этот код

2020-01-22 12:07 UTC, mrPTqp commented on src/main/java/com/study/server/Main.java
> +        Map<String, String> mapping = cr.readMappings();
исправлено

2020-01-22 12:08 UTC, mrPTqp commented on src/main/java/com/study/server/ServerConfiguration.java
> +    private int port;
исправлено. почему я тупил насчет final? потому что я думал, что эти переменные нужно сразу инициализировать

2020-01-22 12:08 UTC, mrPTqp commented on src/main/java/com/study/server/ServerConfiguration.java
> +    private int poolSize;
исправлено

2020-01-22 12:08 UTC, mrPTqp commented on src/main/java/com/study/server/ServerConfiguration.java
> +    private final int defaultPort = 3333;
исправлено

2020-01-22 12:08 UTC, mrPTqp commented on src/main/java/com/study/server/utils/ParsingPatterns.java
> +public class ParsingPatterns {
исправлено

2020-01-22 12:48 UTC, AndreyElagin commented on src/main/java/com/study/server/ConfigurationReaderImpl.java
> +            var hostMatcher = ParsingPatterns.pathHostPattern.matcher(curPath.toString());
Исправь везде пожалуйста. dir.toString вообще не очевидный вариант

2020-01-22 12:55 UTC, mrPTqp commented on src/main/java/com/study/server/ConfigurationReaderImpl.java
> +            var hostMatcher = ParsingPatterns.pathHostPattern.matcher(curPath.toString());
Сорян, пропустил(

2020-01-22 12:55 UTC, mrPTqp commented on src/main/java/com/study/server/ConfigurationReaderImpl.java
> +            var hostMatcher = ParsingPatterns.pathHostPattern.matcher(curPath.toString());
исправлено

2020-01-22 12:59 UTC, merged