44 socket handler
AndreyElagin/http-server-task pull request #6
Opened 2020-01-29 06:47 UTC by mrPTqp

2020-01-29 12:47 UTC, daddyingrave requested changes

2020-01-29 12:47 UTC, daddyingrave commented on src/main/java/com/study/server/HttpServerImpl.java
>          this.port = config.getPort();
А зачем ты везде `this` пишешь? и так понятно что ты к полям класса обращаешься если в локальном контексте (который в большинстве случаев у тебя маленький) нет переменной с таким же названием

2020-01-29 12:47 UTC, daddyingrave commented on src/main/java/com/study/server/HttpServerImpl.java
>          this.port = config.getPort();
Убери везде эти `this`

2020-01-29 12:47 UTC, daddyingrave commented on src/main/java/com/study/server/Main.java
> +        for (Map.Entry<String, String> entry : mappings.entrySet()) {
Перепиши это используя https://docs.oracle.com/javase/8/docs/api/java/lang/Iterable.html#forEach-java.util.function.Consumer-

2020-01-29 12:47 UTC, daddyingrave commented on src/main/java/com/study/server/RequestDispatcherImpl.java
> +        return new HttpResponse(builder);
Я понимаю что этот код не относится к ПРу, но чот не могу понять, почему ты билдер передаешь в конструктор `HttpResponse`? это зачем и почему так?

2020-01-29 12:47 UTC, daddyingrave commented on src/main/java/com/study/server/SocketHandlerFactory.java
> +    ;
?

2020-01-29 12:47 UTC, daddyingrave commented on src/main/java/com/study/server/SocketHandlerFactory.java
> +public class SocketHandlerFactory {
У фабрики тоже должен быть интерфейс

2020-01-29 12:47 UTC, daddyingrave commented on src/main/java/com/study/server/SocketHandlerImpl.java
> +    private RequestDispatcher requestDispatcher;
`final`ы

2020-01-29 12:47 UTC, daddyingrave commented on src/main/java/com/study/server/SocketHandlerImpl.java
> +    private void sendResponse(HttpResponse response) {
1. Этот метод мне кажется здесь не нужен
2. Не уверен что стоит записывать ответ в OutputStream по частям. Мне кажется что у класса `HttpResponse` долежн быть метод который вернет байт массив со всеми полями в нужном порядке

2020-01-29 12:47 UTC, daddyingrave commented on src/main/java/com/study/server/controller/ControllerImpl.java
> +        HttpResponse response = new HttpResponse(builder);
Вопрос был выше

2020-01-29 12:47 UTC, daddyingrave commented on src/test/java/com/study/server/utils/HttpResponseParser.java
> +
?

2020-01-29 12:47 UTC, AndreyElagin commented on src/test/java/com/study/server/sh/SocketHandlerImplTest.java
> +        File file = new File(System.getProperty("user.dir") + "\\src\\test\\resources\\output");
не надо использовать виндовые разделители простигосподи. оно вроде и с человеческими нормально работать должно не? и вообще я не понимаю что ты тут делаешь, почему не писпользуешь getResourceAsStream?

2020-01-29 12:47 UTC, AndreyElagin commented on src/test/java/com/study/server/utils/RequestDispatcherMock.java
> +    static String className;
1. Убери эти поля
2. Создай мапу в которой будешь хранить `HttpRequest` -> количество вызовов метода `dispatch` с таким запросом
3. Создай метод `verifyRequest` который будет принимать `HttpRequest` и говорить сколько раз он был вызыван
4. Создай метод `clearMock` который будет обнулять количество реквестов в мапе из пункта 2

2020-01-29 12:47 UTC, AndreyElagin commented on src/test/java/com/study/server/utils/SocketMock.java
> +        File responseFileName = new File(System.getProperty("user.dir") + "\\src\\test\\resources\\output");
чо это за проперти такое? использую getResourceAsStream или как там оно

2020-01-29 12:47 UTC, AndreyElagin commented on src/test/java/com/study/server/utils/SocketMock.java
> +        File responseFileName = new File(System.getProperty("user.dir") + "\\src\\test\\resources\\output");
И не используй виндовые разделители, вроде же юниксовые нормально работают?

2020-01-29 12:47 UTC, AndreyElagin commented on src/test/java/com/study/server/utils/SocketMock.java
> +public class SocketMock extends Socket {
Нужен методы по аналогии с тем что я описал выше, для верификации и очитки моков

2020-01-29 12:47 UTC, AndreyElagin commented on src/test/java/com/study/server/utils/RequestDispatcherMock.java
> +        final Map<String, String> headers = Map.of(
И сделай респонс по проще

2020-01-29 12:47 UTC, AndreyElagin commented on src/test/java/com/study/server/sh/SocketHandlerImplTest.java
> +    @DisplayName("The method calling RequestDispatcherMock should be com.study.server.SocketHandlerImpl.run")
Твоя задача здесь проверить что SocketHandler отправил в `RequestDispatcher` корректный реквест. Посмотри замечания к мокам и отталкиваясь от этого сделай другие тесты :)

2020-01-31 11:29 UTC, mrPTqp commented on src/main/java/com/study/server/HttpServerImpl.java
>          this.port = config.getPort();
убрал везде this. Думал это обязательно, когда обращаешься к полям класса, ошибался

2020-01-31 11:29 UTC, mrPTqp commented on src/main/java/com/study/server/Main.java
> +        for (Map.Entry<String, String> entry : mappings.entrySet()) {
переписал

2020-01-31 11:29 UTC, mrPTqp commented on src/main/java/com/study/server/RequestDispatcherImpl.java
> +        return new HttpResponse(builder);
исправил как ```HttpResponse``` так и ```HttpRequest```

2020-01-31 11:30 UTC, mrPTqp commented on src/main/java/com/study/server/SocketHandlerFactory.java
> +    ;
:(

2020-01-31 11:30 UTC, mrPTqp commented on src/main/java/com/study/server/SocketHandlerFactory.java
> +public class SocketHandlerFactory {
добавил

2020-01-31 11:30 UTC, mrPTqp commented on src/main/java/com/study/server/SocketHandlerImpl.java
> +    private RequestDispatcher requestDispatcher;
добавил. Также изменил поведение блока try/catch

2020-01-31 11:31 UTC, mrPTqp commented on src/main/java/com/study/server/SocketHandlerImpl.java
> +    private void sendResponse(HttpResponse response) {
метод исключен. в ```HttpResponse``` добавлен метод getPreparedResponse()

2020-01-31 11:31 UTC, mrPTqp commented on src/main/java/com/study/server/controller/ControllerImpl.java
> +        HttpResponse response = new HttpResponse(builder);
исправлено

2020-01-31 11:32 UTC, mrPTqp commented on src/test/java/com/study/server/utils/HttpResponseParser.java
> +
:(:(

2020-01-31 11:33 UTC, mrPTqp commented on src/test/java/com/study/server/sh/SocketHandlerImplTest.java
> +        File file = new File(System.getProperty("user.dir") + "\\src\\test\\resources\\output");
просто для меня виндовые разделители самые привычные) в общем этот код целиком исключен, теперь работа с файлами при проверке выданного в ```OutPutStream HttpResponse``` исключена

2020-01-31 11:33 UTC, mrPTqp commented on src/test/java/com/study/server/utils/RequestDispatcherMock.java
> +    static String className;
всё сделано

2020-01-31 11:34 UTC, mrPTqp commented on src/test/java/com/study/server/utils/SocketMock.java
> +        File responseFileName = new File(System.getProperty("user.dir") + "\\src\\test\\resources\\output");
этот код исключен

2020-01-31 11:34 UTC, mrPTqp commented on src/test/java/com/study/server/utils/SocketMock.java
> +public class SocketMock extends Socket {
добавил

2020-01-31 11:34 UTC, mrPTqp commented on src/test/java/com/study/server/utils/RequestDispatcherMock.java
> +        final Map<String, String> headers = Map.of(
упростил

2020-01-31 11:35 UTC, mrPTqp commented on src/test/java/com/study/server/sh/SocketHandlerImplTest.java
> +    @DisplayName("The method calling RequestDispatcherMock should be com.study.server.SocketHandlerImpl.run")
переделал почти все тесты, учитывая нововведения

2020-01-31 12:32 UTC, AndreyElagin commented on src/main/java/com/study/server/Main.java
> +        for (Map.Entry<String, String> entry : mappings.entrySet()) {
А перепиши вот так примерно:
```
return mappings.entrySet()
                .stream()
                .map(e -> new ControllerImpl(e.getKey(), e.getValue()))
                .collect(Collectors.toSet());
````

2020-02-01 13:03 UTC, daddyingrave requested changes

2020-02-01 13:03 UTC, daddyingrave commented on src/main/java/com/study/server/http/HttpResponse.java
> +    public byte[] getPreparedResponse() {
`toBytes`

2020-02-01 13:03 UTC, daddyingrave commented on src/main/java/com/study/server/SocketHandlerImpl.java
> +            this.in = clientSocket.getInputStream();
Ты же вроде убрал `this`'ы

2020-02-01 13:03 UTC, daddyingrave commented on src/main/java/com/study/server/SocketHandlerImpl.java
> +            var preparedResponse = response.getPreparedResponse();
а зачем тебе эта переменная?

2020-02-01 13:03 UTC, daddyingrave commented on src/main/java/com/study/server/controller/ControllerImpl.java
>  public class ControllerImpl implements Controller {
Как то обсуждали что это не просто `ControllerImpl` это вполне себе конкретный контроллер, тоесть держи в голове что он не один такой может быть, и придумай название в соответсвии с тем, чем данный контроллер может отличаться от других, ну тоесть отталкиваясь от того что он делает (будет делать).

2020-02-01 13:03 UTC, daddyingrave commented on src/main/java/com/study/server/http/HttpRequest.java
> +    private HttpRequest(String method, String path, Map<String, String> queryParameters, String protocol,
Либо все аргументы в одну строку (если позволяет ширина) либо каждый аргумент на отдельной строке.

2020-02-01 13:03 UTC, daddyingrave commented on src/main/java/com/study/server/http/HttpRequestParser.java
> +        var builder = new HttpRequest.RequestBuilder();
Я возможно забыл, но кажется не просил тебя переименовывать билдер?
Вполне логично если ты создаешь экземпляр класса `Builder` через вот такую запись `HttpRequest.Builder()` впонлне себе понятно билдером чего он является.

2020-02-01 13:03 UTC, daddyingrave commented on src/test/java/com/study/server/sh/SocketHandlerImplTest.java
> +        Integer expectedDispatchCalls1 = 1;
а здесь `var` не работает разве?

2020-02-01 13:03 UTC, daddyingrave commented on src/test/java/com/study/server/sh/SocketHandlerImplTest.java
> +        var request = HttpRequestParser.parse(in);
Сделай на моке метод типа `getInterceptedRequests` который тебе вернет распарсенные реквесты, не нужно код теста этим перегружать

2020-02-01 13:03 UTC, daddyingrave commented on src/test/java/com/study/server/sh/SocketHandlerImplTest.java
> +        var rd = new RequestDispatcherMock();
Наверное, есть смысл в названии переменной отразить что это мок. Потому что когда ты дальше по коду вызываешь метод `rd.verifyRequest()` мне пришлось возвращаться снова вверх чтобы понять а что здесь собственно происходит

2020-02-01 13:03 UTC, daddyingrave commented on src/test/java/com/study/server/sh/SocketHandlerImplTest.java
> +    @DisplayName("Should change the number of dispatch() method calls")
Твой тест на самом деле проверяет не то сколько раз дернулся какой то там метод, а он проверяет то что если было получено два корректных входящих запроса то они оба были обработаны

2020-02-01 13:03 UTC, daddyingrave commented on src/test/java/com/study/server/sh/SocketHandlerImplTest.java
> +        assertEquals(expectedDispatchCalls1, dispatchCalls);
И да, надо избегать промежуточных проверок. Смысл теста в том что если было 2 входящих соединнения, то они оба обработались. Ты можешь просто изначально зафиксировать через переменную начальное состояние мока, до всех вызовов и оно должно быть равным 0, а потом проверить что после 2ух вызовов оно стало равным 2

2020-02-01 13:03 UTC, daddyingrave commented on src/test/java/com/study/server/sh/SocketHandlerImplTest.java
> +        assertEquals(expectedDispatchCalls1, dispatchCalls);
Это общая рекоммендация ко всем тестам

2020-02-01 13:03 UTC, daddyingrave commented on src/test/java/com/study/server/sh/SocketHandlerImplTest.java
> +    @DisplayName("Should clear mock")
Не надо тестировать логику работы моков :) Что ты вообще здесь хотел проверить? если то что написано то просто удали этот тест

2020-02-01 13:03 UTC, daddyingrave commented on src/test/java/com/study/server/sh/SocketHandlerImplTest.java
> +    @DisplayName("Should verify request")
Если это тест мока, то удали его

2020-02-01 13:03 UTC, AndreyElagin commented on src/test/java/com/study/server/sh/SocketHandlerImplTest.java
> +    @DisplayName("Should pass expected HttpResponse to OutputStream")
Ну наверное опять же формулирвка теста должна быть более общей. Наверное ты здесь проверяешь, то что на определенный запрос был получен ожидаемый ответ

2020-02-01 13:03 UTC, AndreyElagin commented on src/test/java/com/study/server/sh/SocketHandlerImplTest.java
> +    @DisplayName("Should clear mock")
Не надо тестов на моки

2020-02-01 13:03 UTC, AndreyElagin commented on src/test/java/com/study/server/sh/SocketHandlerImplTest.java
> +    @DisplayName("Should change the number of dispatch () method calls for different HttpRequest")
Смотри комментарии к тесту выше. Здесь они тоже справедливы

2020-02-02 07:14 UTC, mrPTqp commented on src/main/java/com/study/server/Main.java
> +        for (Map.Entry<String, String> entry : mappings.entrySet()) {
Переписал, а это круче?

2020-02-02 07:14 UTC, mrPTqp commented on src/main/java/com/study/server/http/HttpResponse.java
> +    public byte[] getPreparedResponse() {
переименовал

2020-02-02 07:15 UTC, mrPTqp commented on src/main/java/com/study/server/SocketHandlerImpl.java
> +            this.in = clientSocket.getInputStream();
видать не все, но сейчас я взял, открыл каждый файл и проверил на ненужные ```this```. Это было последнее место, я исправил

2020-02-02 07:15 UTC, mrPTqp commented on src/main/java/com/study/server/SocketHandlerImpl.java
> +            var preparedResponse = response.getPreparedResponse();
исключил

2020-02-02 07:17 UTC, mrPTqp commented on src/main/java/com/study/server/controller/ControllerImpl.java
>  public class ControllerImpl implements Controller {
хоть убей, не помню как я его должен был обозвать. HttpController? :)

2020-02-02 07:22 UTC, mrPTqp commented on src/main/java/com/study/server/http/HttpRequest.java
> +    private HttpRequest(String method, String path, Map<String, String> queryParameters, String protocol,
на мой взгляд, правило странноватое, но я исправил

2020-02-02 07:25 UTC, mrPTqp commented on src/main/java/com/study/server/http/HttpRequestParser.java
> +        var builder = new HttpRequest.RequestBuilder();
Это была моя инициатива, и да, ты прав, в разрезе статического метода смысла так именовать нет. Исправил

2020-02-02 07:31 UTC, mrPTqp commented on src/test/java/com/study/server/sh/SocketHandlerImplTest.java
> +        Integer expectedDispatchCalls1 = 1;
работает, то ```var``` определяет тип ```int```, а мне нужен ```Integer```, так как при обращении из метода ```verifyRequest``` класса ```RequestDispatcherMock``` к мапе ```counts``` вернется ```Integer```. Кароч иначе кастить придется просто

2020-02-02 07:39 UTC, mrPTqp commented on src/test/java/com/study/server/sh/SocketHandlerImplTest.java
> +        var request = HttpRequestParser.parse(in);
сделал

2020-02-02 11:55 UTC, mrPTqp commented on src/main/java/com/study/server/controller/ControllerImpl.java
>  public class ControllerImpl implements Controller {
После устного разговора переименовал в ```FileController```

2020-02-02 11:57 UTC, mrPTqp commented on src/test/java/com/study/server/sh/SocketHandlerImplTest.java
> +        Integer expectedDispatchCalls1 = 1;
Исправлено. Метод ```verifyRequest()``` класса ```RequestDispatcherMock``` теперь возвращает ```int```

2020-02-02 11:58 UTC, mrPTqp commented on src/test/java/com/study/server/sh/SocketHandlerImplTest.java
> +        var rd = new RequestDispatcherMock();
переименовал

2020-02-02 11:58 UTC, mrPTqp commented on src/test/java/com/study/server/sh/SocketHandlerImplTest.java
> +    @DisplayName("Should change the number of dispatch() method calls")
переименовал

2020-02-02 11:59 UTC, mrPTqp commented on src/test/java/com/study/server/sh/SocketHandlerImplTest.java
> +        assertEquals(expectedDispatchCalls1, dispatchCalls);
изменил

2020-02-02 11:59 UTC, mrPTqp commented on src/test/java/com/study/server/sh/SocketHandlerImplTest.java
> +    @DisplayName("Should clear mock")
понял, зауважал, удалил

2020-02-02 11:59 UTC, mrPTqp commented on src/test/java/com/study/server/sh/SocketHandlerImplTest.java
> +    @DisplayName("Should verify request")
удалил

2020-02-02 12:00 UTC, mrPTqp commented on src/test/java/com/study/server/sh/SocketHandlerImplTest.java
> +    @DisplayName("Should pass expected HttpResponse to OutputStream")
переименовал

2020-02-02 12:00 UTC, mrPTqp commented on src/test/java/com/study/server/sh/SocketHandlerImplTest.java
> +    @DisplayName("Should clear mock")
удалил

2020-02-02 12:00 UTC, mrPTqp commented on src/test/java/com/study/server/sh/SocketHandlerImplTest.java
> +    @DisplayName("Should change the number of dispatch () method calls for different HttpRequest")
переделал

2020-02-02 12:16 UTC, AndreyElagin commented on src/main/java/com/study/server/Main.java
> +        for (Map.Entry<String, String> entry : mappings.entrySet()) {
Ну обычно так делают после java 8. Учи стримы

2020-02-02 12:17 UTC, AndreyElagin commented on src/main/java/com/study/server/http/HttpRequest.java
> +    private HttpRequest(String method, String path, Map<String, String> queryParameters, String protocol,
Ну вот так вот

2020-02-02 12:22 UTC, daddyingrave approved these changes

2020-02-02 12:24 UTC, merged