43-request-dispatcher
AndreyElagin/http-server-task pull request #8
Opened 2020-02-02 15:44 UTC by mrPTqp

Make Controller interface public. Use Controller interface instead FileController. Change algorithm of dispatch method of RequestDispatcherImpl class. Exclude unnecessary variables. Add ControllerMock to test RequestDispatcherImpl. Add tests for RequestDispatcherImpl. Add createBadRequest method to HttpRequestGenerator for test RequestDispatcherImpl

2020-02-03 20:37 UTC, daddyingrave requested changes

2020-02-03 20:37 UTC, AndreyElagin commented on src/main/java/com/study/server/RequestDispatcherImpl.java
> +    private Set<Controller> controllers;
`final`

2020-02-03 20:37 UTC, AndreyElagin commented on src/main/java/com/study/server/RequestDispatcherImpl.java
>          this.controllers = controllers;
Что будет если `controllers` будет пустым либо равным `null`?

2020-02-03 20:37 UTC, AndreyElagin commented on src/main/java/com/study/server/Main.java
> +    private static Set<Controller> getControllers(Map<String, String> mappings) {
Я думаю что ты можешь заинлайнить этот метод

2020-02-04 06:23 UTC, mrPTqp commented on src/main/java/com/study/server/RequestDispatcherImpl.java
> +    private Set<Controller> controllers;
нужен блин какой-то алгоритм. Типа написал программу, написал тесты, после этого: 1) проверь чтобы всё что можно было final и private; 2) проверь пустые строки; 3) проверь читаемость и выдели/заинлайнь какие-либо методы, при необходимости; и т.д. 
Нету случайно такого в природе?)
Исправил.

2020-02-04 06:23 UTC, mrPTqp commented on src/main/java/com/study/server/Main.java
> +    private static Set<Controller> getControllers(Map<String, String> mappings) {
сделал

2020-02-04 06:28 UTC, mrPTqp commented on src/main/java/com/study/server/RequestDispatcherImpl.java
>          this.controllers = controllers;
По идее у меня такого быть не может, но м.б. я не понимаю чего-то.
У меня controllers передаются в RequestDispatcherImpl из Main. В Main'е controllers формируются на основании mappings, которые берутся из ConfigurationReaderImpl. А вот в этом ConfigurationReaderImpl уже есть проверка на пустоту этих mappings, которая в случае чего бросает NoSuchElementException "The configuration directory does not contain valid site directories". Единственное чо, я исправил сейчас NoSuchElementException на RuntimeException, т.к. NoSuchElementException это checked исключение

2020-02-04 07:10 UTC, AndreyElagin commented on src/main/java/com/study/server/RequestDispatcherImpl.java
> +    private Set<Controller> controllers;
- https://checkstyle.sourceforge.io/
- http://findbugs.sourceforge.net/
- https://pmd.github.io/
Если ты все это или хотя бы что то из этого встроишь в пайплайн Actions то будешь большим молодцом, я хотел именно это попросить Сашу сделать.

2020-02-04 07:12 UTC, AndreyElagin commented on src/main/java/com/study/server/RequestDispatcherImpl.java
>          this.controllers = controllers;
Ну тоесть ты полагаешься на то что абстракция, которая находится на пару уровней выше не протечет? )

2020-02-04 10:11 UTC, mrPTqp commented on src/main/java/com/study/server/RequestDispatcherImpl.java
> +    private Set<Controller> controllers;
Исправлено. 
Добавил задачу в трелло по добавлению указанных тобой инструментов

2020-02-04 10:12 UTC, mrPTqp commented on src/main/java/com/study/server/RequestDispatcherImpl.java
>          this.controllers = controllers;
Понял, зауважал, добавил проверку на null и empty

2020-02-04 20:17 UTC, daddyingrave approved these changes

2020-02-04 20:18 UTC, merged